2020-05-12 16:39:15.295 [error] <0.669.0> CRASH REPORT Process <0.669.0> with 0 neighbours exited with reason: {{{shutdown,{server_initiated_close,406,<<"PRECONDITION_FAILED - inequivalent arg 'x-dead-letter-exchange' for queue 'gen_server_test_queue' in vhost '/': received none but current is the value '' of type 'longstr'">>}},{gen_server,call,[<0.682.0>,{call,{'queue.declare',0,<<"gen_server_test_queue">>,false,true,false,false,false,[]},none,<0.669.0>},60000]}},{'Elixir.User.Plug.Router',call,[#{'__struct__' => 'Elixir.Plug.Conn',adapter => {'Elixir.Plug.Cowboy.Conn',#{bindings => #{},body_length => ...,...}},...},...]}} in 'Elixir.Plug.Cowboy.Handler':exit_on_error/4 line 76 in 'Elixir.Plug.Cowboy.Handler':exit_on_error/4 line 76
2020-05-12 16:39:15.312 [error] <0.669.0> Cowboy stream 1 with ranch listener 'Elixir.User.Plug.Router.HTTP' and connection process <0.668.0> had its request process exit with reason: {{{shutdown,{server_initiated_close,406,<<"PRECONDITION_FAILED - inequivalent arg 'x-dead-letter-exchange' for queue 'gen_server_test_queue' in vhost '/': received none but current is the value '' of type 'longstr'">>}},{gen_server,call,[<0.682.0>,{call,{'queue.declare',0,<<"gen_server_test_queue">>,false,true,false,false,false,[]},none,<0.669.0>},60000]}},{'Elixir.User.Plug.Router',call,[#{'__struct__' => 'Elixir.Plug.Conn',adapter => {'Elixir.Plug.Cowboy.Conn',#{bindings => #{},body_length => ...,...}},...},...]}} in 'Elixir.Plug.Cowboy.Handler':exit_on_error/4 line 76
2020-05-12 16:42:20.522 [error] <0.689.0> CRASH REPORT Process <0.689.0> with 0 neighbours exited with reason: {{{shutdown,{server_initiated_close,406,<<"PRECONDITION_FAILED - inequivalent arg 'x-dead-letter-exchange' for queue 'gen_server_test_queue' in vhost '/': received none but current is the value '' of type 'longstr'">>}},{gen_server,call,[<0.701.0>,{call,{'queue.declare',0,<<"gen_server_test_queue">>,false,true,false,false,false,[]},none,<0.689.0>},60000]}},{'Elixir.User.Plug.Router',call,[#{'__struct__' => 'Elixir.Plug.Conn',adapter => {'Elixir.Plug.Cowboy.Conn',#{bindings => #{},body_length => ...,...}},...},...]}} in 'Elixir.Plug.Cowboy.Handler':exit_on_error/4 line 76 in 'Elixir.Plug.Cowboy.Handler':exit_on_error/4 line 76
2020-05-12 16:42:20.522 [error] <0.689.0> Cowboy stream 1 with ranch listener 'Elixir.User.Plug.Router.HTTP' and connection process <0.688.0> had its request process exit with reason: {{{shutdown,{server_initiated_close,406,<<"PRECONDITION_FAILED - inequivalent arg 'x-dead-letter-exchange' for queue 'gen_server_test_queue' in vhost '/': received none but current is the value '' of type 'longstr'">>}},{gen_server,call,[<0.701.0>,{call,{'queue.declare',0,<<"gen_server_test_queue">>,false,true,false,false,false,[]},none,<0.689.0>},60000]}},{'Elixir.User.Plug.Router',call,[#{'__struct__' => 'Elixir.Plug.Conn',adapter => {'Elixir.Plug.Cowboy.Conn',#{bindings => #{},body_length => ...,...}},...},...]}} in 'Elixir.Plug.Cowboy.Handler':exit_on_error/4 line 76
2020-05-12 17:08:32.416 [error] <0.582.0>@lists:reverse:147 CRASH REPORT Process <0.582.0> with 0 neighbours crashed with reason: no function clause matching lists:reverse({ok,<<"{\"token\":\"eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJhdWQiOiJhdXRoIiwiZXhwIjoxNTkxODg0NTEyLCJp...">>}) line 147
2020-05-12 17:08:32.417 [error] <0.579.0>@lists:reverse:147 Supervisor {<0.579.0>,amqp_channel_sup} had child writer started with rabbit_writer:start_link(#Port<0.16>, 1, 131072, rabbit_framing_amqp_0_9_1, <0.581.0>, {<<"client 127.0.0.1:64373 -> 127.0.0.1:5672">>,1}, false, 1000000000) at <0.582.0> exit with reason no function clause matching lists:reverse({ok,<<"{\"token\":\"eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJhdWQiOiJhdXRoIiwiZXhwIjoxNTkxODg0NTEyLCJp...">>}) line 147 in context child_terminated
2020-05-12 17:08:32.417 [error] <0.579.0> Supervisor {<0.579.0>,amqp_channel_sup} had child writer started with rabbit_writer:start_link(#Port<0.16>, 1, 131072, rabbit_framing_amqp_0_9_1, <0.581.0>, {<<"client 127.0.0.1:64373 -> 127.0.0.1:5672">>,1}, false, 1000000000) at <0.582.0> exit with reason reached_max_restart_intensity in context shutdown
2020-05-12 17:08:32.433 [error] <0.568.0> CRASH REPORT Process <0.568.0> with 0 neighbours exited with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.Protocol.UndefinedError',description => <<>>,protocol => 'Elixir.String.Chars',value => {ok,<<"{\"token\":\"eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJhdWQiOiJhdXRoIiwiZXhwIjoxNTkxODg0NTEyLCJpYXQiOjE1ODkyOTI1MTIsImlzcyI6ImF1dGgiLCJqdGkiOiI1NzM3YmY0ZS03MDU0LTRiZTctODZhYy0xMDhmY2Q3ZGU5M2IiLCJuYmYiOjE1ODkyOTI1MTEsInN1YiI6IjMiLCJ0eXAiOiJhY2Nlc3MifQ.DiwNO2RJZyL3znS1qcGKGO0NBzto06132yxpJXF4iEOfKYPSWPWPSs88Yrjoshvkn-ptZLSWLVMhuldBtuXPbA\",\"last_name\":\"p...">>}},...},...} in 'Elixir.Plug.Cowboy.Handler':exit_on_error/4 line 68 in 'Elixir.Plug.Cowboy.Handler':exit_on_error/4 line 68
2020-05-12 17:08:32.441 [error] <0.568.0> Cowboy stream 1 with ranch listener 'Elixir.User.Plug.Router.HTTP' and connection process <0.567.0> had its request process exit with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.Protocol.UndefinedError',description => <<>>,protocol => 'Elixir.String.Chars',value => {ok,<<"{\"token\":\"eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJhdWQiOiJhdXRoIiwiZXhwIjoxNTkxODg0NTEyLCJpYXQiOjE1ODkyOTI1MTIsImlzcyI6ImF1dGgiLCJqdGkiOiI1NzM3YmY0ZS03MDU0LTRiZTctODZhYy0xMDhmY2Q3ZGU5M2IiLCJuYmYiOjE1ODkyOTI1MTEsInN1YiI6IjMiLCJ0eXAiOiJhY2Nlc3MifQ.DiwNO2RJZyL3znS1qcGKGO0NBzto06132yxpJXF4iEOfKYPSWPWPSs88Yrjoshvkn-ptZLSWLVMhuldBtuXPbA\",\"last_name\":\"p...">>}},...},...} in 'Elixir.Plug.Cowboy.Handler':exit_on_error/4 line 68
